# Configuración del Buscaminas
# Dimensiones del tablero (mínimo 8, máximo 32)
dimensiones=10

# Cantidad de minas (por número o porcentaje, ej: cantidad_minas=40 o cantidad_minas=15%)
cantidad_minas=25
