# Configuracion del Buscaminas
# Dimensiones del tablero (minimo 8, maximo 32)
dimensiones=10

# Cantidad de minas (por numero o porcentaje, ej: cantidad_minas=40 o cantidad_minas=15%)
cantidad_minas=24
